//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgustinaEntities : DbContext
    {
        public AgustinaEntities()
            : base("name=AgustinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimento> Alimento { get; set; }
        public virtual DbSet<DatCli> DatCli { get; set; }
        public virtual DbSet<Diabetes> Diabetes { get; set; }
        public virtual DbSet<Enfermedad> Enfermedad { get; set; }
        public virtual DbSet<HisDatCli> HisDatCli { get; set; }
        public virtual DbSet<HisRelMedRelPerEnf> HisRelMedRelPerEnf { get; set; }
        public virtual DbSet<HisRelPerEnf> HisRelPerEnf { get; set; }
        public virtual DbSet<HisRelUsuRol> HisRelUsuRol { get; set; }
        public virtual DbSet<HisValorDiabetes> HisValorDiabetes { get; set; }
        public virtual DbSet<HisValorObesidad> HisValorObesidad { get; set; }
        public virtual DbSet<Medicina> Medicina { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Obesidad> Obesidad { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<RelMedRelPerEnf> RelMedRelPerEnf { get; set; }
        public virtual DbSet<RelPerEnf> RelPerEnf { get; set; }
        public virtual DbSet<RelUsuRol> RelUsuRol { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Valor> Valor { get; set; }
    }
}
