//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public long AuditoriaId { get; set; }
        public string AuditoriaTabla { get; set; }
        public string AuditoriaUsuario { get; set; }
        public System.DateTime AuditoriaFchHora { get; set; }
        public string AuditoriaTGOP { get; set; }
    }
}
