//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public long ControlId { get; set; }
        public long PersonaId { get; set; }
        public long EnfermedadId { get; set; }
        public long ValorId { get; set; }
        public double ControlValor { get; set; }
    
        public virtual Registro Registro { get; set; }
        public virtual RelEnfVal RelEnfVal { get; set; }
    }
}
