//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dieta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dieta()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public long DietaId { get; set; }
        public double DietaDesayunoCalorias { get; set; }
        public string DietaDesayunoDescripcion { get; set; }
        public double DietaAlmuerzoCalorias { get; set; }
        public string DietaAlmuerzoDescripcion { get; set; }
        public double DietaMeriendaCalorias { get; set; }
        public string DietaMeriendaDescripcion { get; set; }
        public double DietaCenaCalorias { get; set; }
        public string DietaCenaDescripcion { get; set; }
        public double DietaIngestasCalorias { get; set; }
        public string DietaIngestasDescripcion { get; set; }
    
        public virtual Contenido Contenido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
