//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosis
    {
        public long DosisId { get; set; }
        public long MedicinaId { get; set; }
        public long ValorId { get; set; }
        public string DosisTipo { get; set; }
        public double DosisCantidadMin { get; set; }
        public string DosisMedida { get; set; }
        public double DosisEfecto { get; set; }
    
        public virtual RelMedVal RelMedVal { get; set; }
    }
}
