//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisDatCli
    {
        public long HisDatCliId { get; set; }
        public long DatCliId { get; set; }
        public long PersonaId { get; set; }
        public Nullable<double> DatCliPeso { get; set; }
        public Nullable<double> DatCliAltura { get; set; }
        public System.DateTime DatCliFchEnable { get; set; }
    }
}
