//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisDatosDiabetes
    {
        public long HisDatosDiabetesId { get; set; }
        public long DiabetesId { get; set; }
        public long PersonaId { get; set; }
        public System.DateTime DatosFchEnable { get; set; }
        public Nullable<short> DiabetesHidratosPorUniInsu { get; set; }
        public System.DateTime HisDatosDiabetesFchDisable { get; set; }
    }
}
