//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisRelMedRelPerEnf
    {
        public long HisRelMedRelPerEnfId { get; set; }
        public long RelMedRelPerEnfId { get; set; }
        public long PersonaId { get; set; }
        public long EnfermedadId { get; set; }
        public long MedicinaId { get; set; }
        public Nullable<double> RelMedRelPerEnfFrecuencia { get; set; }
        public string RelMedRelPerEnfFrecuenciaTipo { get; set; }
        public System.DateTime RelMedRelPerEnfFchEnable { get; set; }
        public System.DateTime HisRelMedRelPerEnfFchDisable { get; set; }
    }
}
