//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisRelPerEnf
    {
        public long HisRelPerEnfId { get; set; }
        public long PersonaId { get; set; }
        public long EnfermedadId { get; set; }
        public System.DateTime RelPerEnfFchEnable { get; set; }
        public System.DateTime HisRelPerEnfFchDisable { get; set; }
    }
}
