//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisValorObesidad
    {
        public long HisValorObesidadId { get; set; }
        public long ObesidadId { get; set; }
        public long PersonaId { get; set; }
        public System.DateTime ValorFchEnable { get; set; }
        public double ObesidadPesoCorrecto { get; set; }
        public System.DateTime HisValorObesidadFchDisable { get; set; }
    }
}
