//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisValorDiabetes
    {
        public long HisValorDiabetesId { get; set; }
        public long ValorId { get; set; }
        public long PersonaId { get; set; }
        public System.DateTime ValorFchEnable { get; set; }
        public string DiabetesTipo { get; set; }
        public Nullable<double> DiabetesGlicemiaBaja { get; set; }
        public Nullable<double> DiabetesGlicemiaAlta { get; set; }
        public Nullable<short> DiabetesHidratosPorUniInsu { get; set; }
        public System.DateTime HisValorDiabetesFchDisable { get; set; }
    }
}
