//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicacion
    {
        public long MedicacionId { get; set; }
        public long PersonaId { get; set; }
        public long MedicinaId { get; set; }
        public short TomaCantidad { get; set; }
        public string TomaCantidadTipo { get; set; }
    
        public virtual Correccion Correccion { get; set; }
        public virtual Retardada Retardada { get; set; }
        public virtual Registro Registro { get; set; }
        public virtual Medicina Medicina { get; set; }
    }
}
