//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public long NotificacionId { get; set; }
        public long UsuarioId { get; set; }
        public short TemaNotId { get; set; }
        public string NotificacionTitulo { get; set; }
        public string NotificacionDescripcion { get; set; }
        public System.DateTime NotificacionFchHora { get; set; }
        public bool NotificacionVista { get; set; }
    
        public virtual TemaNot TemaNot { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
