//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recordatorio()
        {
            this.Repeticion = new HashSet<Repeticion>();
            this.Dia = new HashSet<Dia>();
        }
    
        public long RecordatorioId { get; set; }
        public long PersonaId { get; set; }
        public System.DateTime RecordatorioFchIni { get; set; }
        public string RecordatorioNombre { get; set; }
        public string RecordatorioDesc { get; set; }
        public Nullable<short> RecordatorioRepTiempo { get; set; }
        public string RecordatorioRepTiempoTipo { get; set; }
        public Nullable<short> RecordatorioNotAvisarTiempo { get; set; }
        public string RecordatorioNotAvisarTiempoTipo { get; set; }
        public bool RecordatorioNotApp { get; set; }
        public bool RecordatorioNotEmail { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repeticion> Repeticion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dia> Dia { get; set; }
        public virtual Medicina Medicina { get; set; }
    }
}
