//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public long RegistroId { get; set; }
        public long PersonaId { get; set; }
        public System.DateTime RegistroFchHora { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Agua Agua { get; set; }
        public virtual Comida Comida { get; set; }
        public virtual Control Control { get; set; }
        public virtual DatCli DatCli { get; set; }
        public virtual Medicacion Medicacion { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Peso Peso { get; set; }
    }
}
