//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelPerEnf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelPerEnf()
        {
            this.RelMedRelPerEnf = new HashSet<RelMedRelPerEnf>();
        }
    
        public long PersonaId { get; set; }
        public long EnfermedadId { get; set; }
        public System.DateTime RelPerEnfFchEnable { get; set; }
    
        public virtual Enfermedad Enfermedad { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelMedRelPerEnf> RelMedRelPerEnf { get; set; }
    }
}
