//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelUsuPer
    {
        public long UsuarioId { get; set; }
        public long PersonaId { get; set; }
        public System.DateTime RelUsuPerFchEnable { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
